[BUG] Fixed team feedback bugs
neurobagel/old-query-tool pull request #100
Opened 2023-06-06 15:26 UTC by rmanaem

Fixes #95 
Fixes #96 
See also #94 

Changes proposed in this pull request:

- Implemented a condition to give an error message via toast when the value of the minimum number of sessions is set to 0 in `validateQueryForm` 
- Implemented a test case for the above in the `QueryForm` component test
- Implemented a quick fix for #96, to replace `\n` escape character in `dataset_name` with a space
- Implemented `DatasetResultsTSV` e2e test for the above

## Checklist

- [ ] PR has an interpretable title with a prefix (`[ENH]`, `[BUG]`, `[DOC]`, `[INFRA]`, `[MAINT]`)
- [ ] PR links to Github issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Code is properly formatted

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

2023-06-06 20:59 UTC, surchs requested changes
Thanks a lot for the PR @rmanaem! All looks very good, thanks for figuring out how to test these bugs! I requested changes mostly because I think we should disallow bad session-numbers (i.e. `0`) to be entered in the query-form in the first place - and because I think the test assertions should be looked over again.

2023-06-06 20:59 UTC, surchs commented on components/DownloadResultsButton.vue
> +      element.setAttribute('href', `data:text/tab-separated-values;charset=utf-8,
interesting. was that incorrect before?

2023-06-06 20:59 UTC, surchs commented on components/DownloadResultsButton.vue
> +            res.dataset_name.replace('\n', ' '),
like we said today: I think this is an appropriate fix for the specific problem. I also think that we should find a more generic way of addressing the problem without changing data that we pass to the user. E.g. by encapsulating everything in a string. Maybe we can add a TODO here with a link to the issue / PR to revisit this problem in the near future?

2023-06-06 20:59 UTC, surchs commented on components/QueryForm.vue
> +        this.displayToast('The value for minimum number of sessions field must be greater than 0');
just to check: can we not set this as a constraint on the field itself (i.e. like we disallow negative values)?

2023-06-06 20:59 UTC, surchs commented on components/QueryForm.vue
> +        this.displayToast('The value for minimum number of sessions field must be greater than 0');
hhm, I see `min` as an attribute to `<b-form-input>` in the `continuousField.vue` component. That seems to me as if we should be able to explicitly set the constraint there by having a local default that can be overridden by the calling parent, no?

2023-06-06 20:59 UTC, surchs commented on cypress/component/QueryForm.cy.js
> +    cy.get('[data-cy="Minimum number of sessions-continuous-field-input"]').type(0);
Those `data-cy` names don't seem right to me. Are you sure there are elements with these names? Or maybe I am missing something

2023-06-06 20:59 UTC, surchs commented on cypress/component/QueryForm.cy.js
> +    cy.get('[data-cy="Min Age-continuous-field-input"]').clear();
I like these tests, but I think we should start splitting them up. There is a lot going on here already with minimum and maximum age. Better to handle each field in its own test (i.e. 1: `"out of bounds age raises a toast UI element"` and 2: `"session number below 0 raises display toast"`). These tests should be short and with a single purpose

2023-06-06 20:59 UTC, surchs commented on cypress/e2e/DatasetResultsTSV.cy.js
> +  it('Intercepts the request sent to the API and asserts over the request url', () => {
I think the test name should describe the behavioural process rather than the implementation. So "Removes a newline character from the downloaded results file if one is present in the data" or something like that.

2023-06-06 20:59 UTC, surchs commented on cypress/e2e/DatasetResultsTSV.cy.js
> +    cy.readFile('cypress/downloads/dataset-results.tsv').should('not.contain', 'some\nname');
Very neat! However: the assertion would also be true if your code just nuked the `"some name"` string completely out of existence - which is not what we want. So I think it'd make more sense to assert that `"some name"` **does** exist as well (or only, if you know that it only occurs this once)

2023-06-07 15:29 UTC, rmanaem commented on components/DownloadResultsButton.vue
> +      element.setAttribute('href', `data:text/tab-separated-values;charset=utf-8,
It wasn't the standard MIME type

2023-06-07 15:35 UTC, rmanaem commented on components/QueryForm.vue
> +        this.displayToast('The value for minimum number of sessions field must be greater than 0');
Are you saying add a `min` prop to the `continuousField.vue` component that overwrites the `min` attribute of the `<b-form-input`? I like that

2023-06-07 15:37 UTC, rmanaem commented on components/DownloadResultsButton.vue
> +            res.dataset_name.replace('\n', ' '),
Could you create an issue with a short description of what you had in mind? I prefer not to have TODOs in code as they tend to go unnoticed.

2023-06-07 15:39 UTC, rmanaem commented on cypress/component/QueryForm.cy.js
> +    cy.get('[data-cy="Minimum number of sessions-continuous-field-input"]').type(0);
Yea, it's the `name` of the field which is also used as the label separated by `-`, concatenated with the type of field `continuous` or `categorical` separated by `-`, and concatenated by the type of html element

2023-06-07 15:40 UTC, surchs commented on components/QueryForm.vue
> +        this.displayToast('The value for minimum number of sessions field must be greater than 0');
yeah, I think so. If you make it a prop, then I'd make the default whatever it currently is (presumably `0`) to not accidentally break things

2023-06-07 15:42 UTC, rmanaem commented on cypress/e2e/DatasetResultsTSV.cy.js
> +  it('Intercepts the request sent to the API and asserts over the request url', () => {
Are you referring to the `describe` or the `it`?

2023-06-07 15:47 UTC, surchs commented on cypress/e2e/DatasetResultsTSV.cy.js
> +  it('Intercepts the request sent to the API and asserts over the request url', () => {
`it`

2023-06-07 17:04 UTC, rmanaem commented on cypress/component/QueryForm.cy.js
> +    cy.get('[data-cy="Min Age-continuous-field-input"]').clear();
Removing the part for the `minimum number of sessions` field now that we're using a prop.

2023-06-07 17:50 UTC, surchs commented
@rmanaem I don't think you commited any changes. Did you mean to push them still or do you want me to review just based on your comments?

2023-06-07 17:54 UTC, rmanaem commented
This is weird, see [branch history](https://github.com/neurobagel/query-tool/commits/bug-95-96)

2023-06-07 17:57 UTC, rmanaem commented
There we go

2023-06-07 18:03 UTC, surchs approved these changes
Looks good @rmanaem. Noticed that we now have no test for number-session  field. I think that'd be good to add. Otherwise good to go :cook:

2023-06-07 18:03 UTC, surchs commented on cypress/component/QueryForm.cy.js
> -    cy.get('[data-cy="Min Age-continuous-field-input"]').clear();
ok, cool. But now we don't have any test for the feature of "cannot enter < 1 into session field". That's not ideal either. Mind adding a test for that?

2023-06-07 18:23 UTC, rmanaem commented on cypress/component/QueryForm.cy.js
> -    cy.get('[data-cy="Min Age-continuous-field-input"]').clear();
I don't think it's possible to test that. If you recall we talked about this when implementing `continuousField` component which at that time set the `min` attribute to 0 and there wasn't a way to test for that in cypress.

2023-06-07 18:38 UTC, surchs commented on cypress/component/QueryForm.cy.js
> -    cy.get('[data-cy="Min Age-continuous-field-input"]').clear();
aha. good point. In that case: :cook: !

2023-06-07 18:45 UTC, merged