[ENH]: add breakpoints
neurobagel/old-query-tool pull request #105
Opened 2023-06-08 23:05 UTC by joshunrau

Changes proposed in this pull request:
- Add breakpoints to `QueryForm` and `ResultsContainer` so they will not break on mobile
- Change column sizes for large screens so the UI will not break on smaller "xl" screens. For example, on my 13" Macbook, the query panel is very small and the "Healthy control" checkbox overflows.

## Checklist

- [ ] PR has an interpretable title with a prefix (`[ENH]`, `[BUG]`, `[DOC]`, `[INFRA]`, `[MAINT]`)
- [ ] PR links to Github issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Code is properly formatted

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

2023-06-14 20:10 UTC, rmanaem requested changes
Hey @joshunrau, thanks a lot for your first submission to Neurobagel! Happy to have you here :tada:, we appreciate your input. I think your suggestion to add breakpoints makes sense here, thanks for the PR. However: the query form columns with your PR are now quite a bit wider than they were before when seen on a normal-sized desktop viewport. Since we're optimizing viewing experience for larger screens, could you please adjust the changes to make the query fields less wide?

Let me know if you have time to address this, we'll be happy to merge with these changes

2023-06-15 00:12 UTC, joshunrau commented
Okay I changed it back. I would suggest looking into implementing an xxl breakpoint size since on a borderline xxl screen these breakpoints don't look very good imo

2023-06-15 15:53 UTC, rmanaem commented
Yea, the overall layout needs some work.

2023-06-15 15:53 UTC, rmanaem approved these changes
🧑‍🍳

2023-06-15 15:53 UTC, merged