Implemented UI elements for age
neurobagel/old-query-tool pull request #27
Opened 2023-01-22 21:19 UTC by rmanaem

Closes #14

2023-01-24 00:58 UTC, surchs requested changes
Very cool PR @rmanaem :tada: ! I gave based on the assumption that we aren't rushing this out - so I commented on your tests and the app structure. Neither of these impacts function. But splitting the components will make the app structure more maintainable, and writing tests that cover the actual functionality will help with development in the future. Ideally the tests are how you specify for yourself what the app will do before you implement that functionality - that's where we want to get.

That said: all looks very nice and functional. Great job!

2023-01-24 00:58 UTC, surchs commented on components/QueryForm.vue
> +      id="query-fields-column"
Could you explain why you are setting `id` manually here?

2023-01-24 00:58 UTC, surchs commented on components/QueryForm.vue
> +      <b-row>
I think this would be more maintainable if you turned the results section into its own component and then reference it on the index.vue page. This would also make the current name of this component (`QueryForm`) more specific, because the component would only be about the query form and the logic related to the query there.

2023-01-24 00:58 UTC, surchs commented on components/QueryForm.vue
> +        const resp = await this.$axios.get(url);
very neat

2023-01-24 00:58 UTC, surchs commented on cypress/support/bootstrap-vue.js
> +import Vue from 'vue';
Is this file only necessary because you're using bootstrap as a nuxt-module?

2023-01-24 00:58 UTC, surchs commented on cypress/support/component.js
> +// Import BootstrapVue
Can you explain why you need to import bootstrap here? And also why you are importing it from this file (that you created for that exact purpose, I believe)?

2023-01-24 00:58 UTC, surchs commented on cypress/component/AgeField.cy.js
> +    cy.get("[data-cy='maxAge']").should('be.visible');
visible is indeed useful. But I think it would also make sense to check the functionality you have defined (not the component itself). So e.g.: 
- you want the component to only accept numbers, does it?
- you don't want the value to be negative, what happens when you try anyway?

Ideally you write these tests as you are developing the app, so you can clarify your intention, and then see that the code you write addresses the goal you had set for yourself.

2023-01-24 00:58 UTC, surchs commented on cypress/component/AgeField.cy.js
> +    cy.get("[data-cy='maxAge']").should('be.visible');
Oh, and most importantly: you want to make sure that your own component actually emits the correct event with the correct payload in the right situation. You can use the snippets here for some examples: https://github.com/neurobagel/documentation/wiki/Cypress-Test-Snippets#listen-for-an-emitted-event

2023-01-24 00:58 UTC, surchs commented on cypress/component/QueryForm.cy.js
> +  });
Same thing here, you do have a good bit of functionality now that this component handles. Most importantly the API call. So there should be a test to assert that when I hit the "Query" button, an API call indeed will go out.

2023-01-24 00:58 UTC, surchs commented on .eslintrc.js
> +  ignorePatterns: 'cypress.config.js',
Cool, didn't know about this. Do you prefer that over a dedicated `.eslintignore` file?

2023-01-24 00:58 UTC, surchs commented on README.md
> +## Usage
Nice

2023-01-24 00:58 UTC, surchs commented on README.md
> +Once you've defind your criteria, submit them as a query and query tool will display the results.
```suggestion
Once you've defined your criteria, submit them as a query and query tool will display the results.
```

2023-01-24 00:59 UTC, surchs commented on cypress/support/component.js
> +// Import BootstrapVue
Just to clarify: I mean "can you explain that in this comment", because right now the comment only tells me things I can understand from reading the code itself

2023-01-24 16:34 UTC, rmanaem commented on components/QueryForm.vue
> +      id="query-fields-column"
The `id` is for the custom styles that will be added to the `index` page
I plan to go over them after everything is implemented and remove whatever is not needed.

2023-01-24 16:38 UTC, rmanaem commented on components/QueryForm.vue
> +      <b-row>
Yea already done, will show up in the next PR.
Just wanted it to look like the old UI before the `Results` component was added.

2023-01-24 16:38 UTC, rmanaem commented on components/QueryForm.vue
> +        const resp = await this.$axios.get(url);
Thanks!

2023-01-24 16:43 UTC, rmanaem commented on cypress/support/bootstrap-vue.js
> +import Vue from 'vue';
No, the file itself is not required but the imports are required (regardless of whether bootstrap is used as a nuxt module or a plugin) for cypress to apply bootstrap styles in tests.
I added the imports as a file to keep `component.js` clean

2023-01-24 16:45 UTC, rmanaem commented on README.md
> +Once you've defind your criteria, submit them as a query and query tool will display the results.
Good catch

2023-01-24 16:46 UTC, rmanaem commented on .eslintrc.js
> +  ignorePatterns: 'cypress.config.js',
Yea I prefer to have it all in one place.

2023-01-24 16:52 UTC, rmanaem commented on cypress/support/component.js
> +// Import BootstrapVue
> Can you explain why you need to import bootstrap here? And also why you are importing it from this file (that you created for that exact purpose, I believe)?

For cypress to apply bootstrap styles, bootstrap needs to be imported into cypress (in this case component context). I added the imports as a file to keep `component.js` clean.

> Just to clarify: I mean "can you explain that in this comment", because right now the comment only tells me things I can understand from reading the code itself

Will do

2023-01-24 16:57 UTC, rmanaem commented on cypress/component/QueryForm.cy.js
> +  });
>  Most importantly the API call. So there should be a test to assert that when I hit the "Query" button, an API call indeed will go out.

Wouldn't checking that require an integration test?

2023-01-24 18:19 UTC, surchs commented on cypress/component/QueryForm.cy.js
> +  });
Hhm, good question. I don't think so here. You're still just checking the code within the component. I'm thinking about it from the perspective of writing the test before you do the implementation - which is the goal. 

So one would probably be: "when I click the submit button, axios should fire a request somewhere". Doesn't matter if that request is successful, but you want to make sure that your component correctly handles its own responsibilities - which currently include firing axios requests.

I think the integration test would be to assert that provided your axios request was successful (i.e. mocked), some other component of the app would now update with the results (e.g. the results component). So there the concern isn't: "is my component meeting its own responsibilities" but more "is my component playing nice with others"

2023-01-24 20:00 UTC, rmanaem commented on cypress/component/AgeField.cy.js
> +    cy.get("[data-cy='maxAge']").should('be.visible');
I think in the case of AgeField.vue (and perhaps other fields), testing for functionality is trivial since the component is simple. The functionality comes packaged with HTML elements and the component and its implementation doesn't add anything to be tested e.g.,
> you want the component to only accept numbers, does it?

Since the `input` element's `type` property is set to number it doesn't allow for anything other than number input.

> you don't want the value to be negative, what happens when you try anyway?

Something I forgot to take into consideration so thanks for mentioning but it can be added with [`min`](https://www.w3schools.com/tags/att_input_min.asp) property on the `input` element.

That being said I think having an assertion for the emit is a good idea and good practice.

2023-01-25 03:21 UTC, rmanaem commented on cypress/component/QueryForm.cy.js
> +  });
> when I click the submit button, axios should fire a request somewhere

I see, do you have any resources on how we could test for that cause I've been looking around but haven't been able to find anything on that.

I may have taken your example literally, do you mean test if the `updateAge` function is executed i.e. `spy`?

2023-01-25 18:46 UTC, surchs commented on cypress/component/QueryForm.cy.js
> +  });
Hey, sorry for the late response here. I think the relevant cypress docs would be here: https://docs.cypress.io/guides/guides/network-requests. And if you wanted to also test that the results get rendered after a successful request, you'd need to stub the request (https://docs.cypress.io/guides/guides/network-requests#Stubbing).

I think for now, just asserting that a request is in fact sent to the expected URL would be enough.

2023-01-25 18:55 UTC, surchs commented on cypress/component/AgeField.cy.js
> +    cy.get("[data-cy='maxAge']").should('be.visible');
I think a good rule of thumb is: if it can breaks because you've done something wrong, then test it. So if you have to set a parameter to make it request only positive numbers, then that's a piece of code you wrote. If you ever feel inclined to remove these constraints because you don't remember why they matter, the test will be there for you and yell at you. In that sense the test is just a code form of your requirements: this component should let me enter numbers, but not letters, and the numbers should be positive. 

You shouldn't test things that are maintained by someone else and are their problem if they break. So you shouldn't test is whether adding and removing the integer constraint for this specific component actually allows and disallows you adding things other than numbers.

2023-01-25 20:01 UTC, rmanaem commented on cypress/component/QueryForm.cy.js
> +  });
Refer to #26

2023-01-25 20:51 UTC, rmanaem commented on cypress/component/AgeField.cy.js
> +    cy.get("[data-cy='maxAge']").should('be.visible');
Test for text input is implemented.
See #28 for testing negative input.

2023-01-26 18:33 UTC, surchs commented on cypress/component/AgeField.cy.js
> +  it('Types text into the age input fields', () => {
```suggestion
  it('Ignores when text is entered into the age input fields', () => {
```

2023-01-26 18:33 UTC, surchs approved these changes
Looks great @rmanaem! I made one suggestion for a test name, with that good to go! :tada:

2023-01-26 18:42 UTC, merged