[ENH] Encode selected query nodes as query parameters in URL
neurobagel/old-query-tool pull request #303
Opened 2023-11-24 23:44 UTC by surchs

- Closes #302

Changes proposed in this pull request:

- at the beginning of the lifecycle, right after reading node-list from f-API, parse the current browser URL for `node` query parameters
- if `node` query parameters exist, then see if they describe available nodes
- if they don't, default to the "All" node
- if they do, set these nodes to selected immediately
- make all of this reactive (i.e. if user selects nodes in dropdown, URL changes and vice versa)
- change how nodes are represented internally to be an array (of exactly the same shape as the response object from the f-API/nodes endpoint)
- work around the "All" node not having a defined ApiURL

**Note**: due to running out of brain juice this PR does not have any tests for this new functionality. That's a problem and we should fix it either before we merge or directly after. The challenging bit is going to be intercepting the URLs and environment variables.

## Checklist

- [ ] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see https://neurobagel.org/contributing/pull_requests for more info)_
- [ ] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

2023-11-27 19:20 UTC, rmanaem requested changes
Thanks for the PR @surchs! 
I left a couple comments, please take a look. 
Aside from those, I noticed an issue with the `isFederationAPI` when its explicitly set to false in the `.env`.
The value is correctly determined to be false in the `index.vue` but appears as true in the `QueryForm` therefore the `div` containing the Neurobagel graph dropdown gets rendered. Would you mind looking into this?

2023-11-27 19:20 UTC, rmanaem commented on pages/index.vue
> +        });
I think this doesn't take the case where all options have been cleared from the `v-select` into account when it updates the router.

2023-11-27 19:20 UTC, rmanaem commented on pages/index.vue
> +      // TODO: write a test for all these fancy things
I see you added a TODO for tests. Is that because the changes in this PR are time sensitive?

2023-11-27 19:20 UTC, rmanaem commented on pages/index.vue
> +      // TODO: write a test for all these fancy things
Or figuring out how to test these changes wouldn't be worthwhile at the moment?

2023-11-27 19:20 UTC, rmanaem commented on components/QueryForm.vue
> +      if (this.isFederationAPI && this.selectedNodes.length > 0) {
Not sure if we need to check for `isFederationAPI` as when its set to false, the `selectedNodes` would never be updated and its default value would render this condition false.

2023-11-27 19:38 UTC, rmanaem commented
> Aside from those, I noticed an issue with the isFederationAPI when its explicitly set to false in the .env.
The value is correctly determined to be false in the index.vue but appears as true in the QueryForm therefore the div containing the Neurobagel graph dropdown gets rendered. Would you mind looking into this?

It seems this stems from not following the vue prop naming conventions so changing the prop to `isFederationApi` should fix it.

2023-11-27 21:28 UTC, surchs commented on pages/index.vue
> +        });
good point!

2023-11-27 22:02 UTC, surchs commented on pages/index.vue
> +      // TODO: write a test for all these fancy things
Tests we should write:
component
- query form component test for select-nodes
  - emit new event
  - render props nicely
e2e
- the new URL query pushing thing
- setting isFederationApi to false should actually work as intended
-

2023-11-27 23:24 UTC, surchs commented
> > Aside from those, I noticed an issue with the isFederationAPI when its explicitly set to false in the .env.
> > The value is correctly determined to be false in the index.vue but appears as true in the QueryForm therefore the div containing the Neurobagel graph dropdown gets rendered. Would you mind looking into this?
> 
> It seems this stems from not following the vue prop naming conventions so changing the prop to `isFederationApi` should fix it.

For posterity / clarity: what's happening here is:
- https://eslint.vuejs.org/rules/attribute-hyphenation.html requires that props are passed with hyphenation
- we therefore pass `isFederatedAPI` to the `QueryForm.vue` component as `is-federated-api`
- when the `QueryForm.vue` component retrieves the prop, it unpacks it as `isFederatedApi`, presumably because the fact that all last three characters were capitalized is lost and it just defaults to camelCase
- we don't use `isFederatedApi` in the `QueryForm.vue` component, but we do use `isFederatedAPI` - which is now unset
- because `isFederatedAPI` also has a default value, and because this default value is `true`, we have now created a situation where `isFederatedAPI` is always going to be true inside the component (because it will never receive a prop value)

Therefore the only solution is to rename `isFederatedAPI` -> `isFederatedApi` **inside** of `QueryForm.vue`. Also renaming it in `index.vue` is entirely optional, but probably a better idea for consistency's sake.

2023-11-27 23:30 UTC, surchs commented
@rmanaem about testing `isFederationAPI` being correctly parsed from the environment: I think this is trickier than just using `Cypress.env` and I'd rather address it in a future PR than holding this up until we understand it.

e.g. this (somewhat reasonable looking test) does not work:

```js
describe('API request', () => {
  it('Parses the isFederationApi environment variable correctly', () => {
    cy.visit('/');
    Cypress.env('isFederationApi', false);
    cy.get('[data-cy="node-field"]').should('not.exist');
    Cypress.env('isFederationApi', true);
    cy.get('[data-cy="node-field"]').should('exist');
  });
});
```

This could have to do with the fact that although `isFederationApi` is a computed property:

```js
computed: {
    isFederationApi() {
      return this.$config.isFederationAPI === undefined ? true : this.$config.isFederationAPI;
    },
  },
```
it has no way of detecting a change in the environment and only is read / updated once. Or maybe I'm not setting the `.env` correctly. Either way, we should investigate after this is merged!

2023-11-28 20:05 UTC, rmanaem approved these changes
:cook:

2023-11-28 20:20 UTC, merged